project:
  type: website
  output-dir: docs

website:
  title: "Under Par Analytics LLC"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact Us
     
    
      
  open-graph: true

format:
  html:
    theme: simplex
    css: styles.css
    toc: false

editor: visual
  